package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private Integer id;
     private Equipo equipoByIdEquipoUnoFk;
     private Equipo equipoByIdEquipoDosFk;
     private Reserva reserva;
     private Sede sede;
     private String nombre;
     private Date fecha;
     private String hora;
     private Set equipos = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(Equipo equipoByIdEquipoUnoFk, Equipo equipoByIdEquipoDosFk, Reserva reserva, Sede sede, String nombre, Date fecha, String hora) {
        this.equipoByIdEquipoUnoFk = equipoByIdEquipoUnoFk;
        this.equipoByIdEquipoDosFk = equipoByIdEquipoDosFk;
        this.reserva = reserva;
        this.sede = sede;
        this.nombre = nombre;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Actividad(Equipo equipoByIdEquipoUnoFk, Equipo equipoByIdEquipoDosFk, Reserva reserva, Sede sede, String nombre, Date fecha, String hora, Set equipos) {
       this.equipoByIdEquipoUnoFk = equipoByIdEquipoUnoFk;
       this.equipoByIdEquipoDosFk = equipoByIdEquipoDosFk;
       this.reserva = reserva;
       this.sede = sede;
       this.nombre = nombre;
       this.fecha = fecha;
       this.hora = hora;
       this.equipos = equipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipo getEquipoByIdEquipoUnoFk() {
        return this.equipoByIdEquipoUnoFk;
    }
    
    public void setEquipoByIdEquipoUnoFk(Equipo equipoByIdEquipoUnoFk) {
        this.equipoByIdEquipoUnoFk = equipoByIdEquipoUnoFk;
    }
    public Equipo getEquipoByIdEquipoDosFk() {
        return this.equipoByIdEquipoDosFk;
    }
    
    public void setEquipoByIdEquipoDosFk(Equipo equipoByIdEquipoDosFk) {
        this.equipoByIdEquipoDosFk = equipoByIdEquipoDosFk;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }




}


