package gestionActividades;
// Generated 08-may-2021 10:30:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Deporte generated by hbm2java
 */
public class Deporte  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int numJugadores;
     private String descripcion;
     private boolean i;
     private Set actividads = new HashSet(0);

    public Deporte() {
    }

	
    public Deporte(String nombre, int numJugadores, String descripcion, boolean i) {
        this.nombre = nombre;
        this.numJugadores = numJugadores;
        this.descripcion = descripcion;
        this.i = i;
    }
    public Deporte(String nombre, int numJugadores, String descripcion, boolean i, Set actividads) {
       this.nombre = nombre;
       this.numJugadores = numJugadores;
       this.descripcion = descripcion;
       this.i = i;
       this.actividads = actividads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNumJugadores() {
        return this.numJugadores;
    }
    
    public void setNumJugadores(int numJugadores) {
        this.numJugadores = numJugadores;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isI() {
        return this.i;
    }
    
    public void setI(boolean i) {
        this.i = i;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


