package gestionActividades;
// Generated 08-may-2021 10:30:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer id;
     private Pago pago;
     private Usuario usuario;
     private Date fecha;
     private Set actividads = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(Pago pago, Usuario usuario, Date fecha) {
        this.pago = pago;
        this.usuario = usuario;
        this.fecha = fecha;
    }
    public Reserva(Pago pago, Usuario usuario, Date fecha, Set actividads) {
       this.pago = pago;
       this.usuario = usuario;
       this.fecha = fecha;
       this.actividads = actividads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pago getPago() {
        return this.pago;
    }
    
    public void setPago(Pago pago) {
        this.pago = pago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


