package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int activo;
   


    public Equipo() {
    }

	
    public Equipo( String nombre, int activo) {
      
        this.nombre = nombre;
        this.activo=activo;
    }

    public Equipo(Integer id, String nombre, int activo) {
        
        this.id=id;
        this.nombre=nombre;
        this.activo=activo;
    }

    public int getActivo() {
        return activo;
    }

    public void setActivo(int activo) {
        this.activo = activo;
    }


   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   



}


