package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer id;
     private String metodoPago;
     private double importe;
     private int pagado;
     private Date fecha;
  private Reserva reserva;

    public Pago() {
    }

	
    public Pago(String metodoPago, double importe, int pagado, Date fecha) {
        this.metodoPago = metodoPago;
        this.importe = importe;
        this.pagado = pagado;
        this.fecha = fecha;
    }
    public Pago(String metodoPago, double importe, int pagado, Date fecha, Reserva reserva) {
       this.metodoPago = metodoPago;
       this.importe = importe;
       this.pagado = pagado;
       this.fecha = fecha;
       this.reserva = reserva;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(int importe) {
        this.importe = importe;
    }
    public double getPagado() {
        return this.pagado;
    }
    
    public void setPagado(int pagado) {
        this.pagado = pagado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Reserva getReserva() {
        return reserva;
    }

    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


