package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer id;
     private String metodoPago;
     private double importe;
     private double pagado;
     private Date fecha;
     private Set reservas = new HashSet(0);

    public Pago() {
    }

	
    public Pago(String metodoPago, double importe, double pagado, Date fecha) {
        this.metodoPago = metodoPago;
        this.importe = importe;
        this.pagado = pagado;
        this.fecha = fecha;
    }
    public Pago(String metodoPago, double importe, double pagado, Date fecha, Set reservas) {
       this.metodoPago = metodoPago;
       this.importe = importe;
       this.pagado = pagado;
       this.fecha = fecha;
       this.reservas = reservas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public double getPagado() {
        return this.pagado;
    }
    
    public void setPagado(double pagado) {
        this.pagado = pagado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


