package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String direccion;
     private int cp;
     private String tlf;
     private String email;
     private String provincia;
     private Set actividads = new HashSet(0);

    public Sede() {
    }

	
    public Sede(String nombre, String direccion, int cp, String tlf, String email, String provincia) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.cp = cp;
        this.tlf = tlf;
        this.email = email;
        this.provincia = provincia;
    }
    public Sede(String nombre, String direccion, int cp, String tlf, String email, String provincia, Set actividads) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.cp = cp;
       this.tlf = tlf;
       this.email = email;
       this.provincia = provincia;
       this.actividads = actividads;
    }

    public Sede(int id, String nombre, String direccion, int cp, String tlf, String email, String provincia) {
        this.id=id;
        this.nombre = nombre;
       this.direccion = direccion;
       this.cp = cp;
       this.tlf = tlf;
       this.email = email;
       this.provincia = provincia;
       this.actividads = actividads;
    }



   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getActividads() {
        return this.actividads;
    }
    
    public void setActividads(Set actividads) {
        this.actividads = actividads;
    }




}


