package gestionActividades;
// Generated 16-may-2021 10:37:05 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String userName;
     private String password;
     private String nombre;
     private String apellidos;
     private String dni;
     private String email;
     private String tlf;
     private double admin;
     private Set reservas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String userName, String password, String nombre, String apellidos, String dni, String email, String tlf, double admin) {
        this.userName = userName;
        this.password = password;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.dni = dni;
        this.email = email;
        this.tlf = tlf;
        this.admin = admin;
    }
    public Usuario(String userName, String password, String nombre, String apellidos, String dni, String email, String tlf, double admin, Set reservas) {
       this.userName = userName;
       this.password = password;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dni = dni;
       this.email = email;
       this.tlf = tlf;
       this.admin = admin;
       this.reservas = reservas;
    }

    public Usuario(String metodoPago, double importe, double pagado, Date fecha) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTlf() {
        return this.tlf;
    }
    
    public void setTlf(String tlf) {
        this.tlf = tlf;
    }
    public double getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(double admin) {
        this.admin = admin;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


